name = "simple-agent-framework-api"
compatibility_date = "2024-03-17"
workers_dev = true

[build]
command = "pip install -r requirements.txt"

[env.production]
name = "simple-agent-framework-api-prod"
# Add your production environment variables here
vars = { ENVIRONMENT = "production" }

[env.development]
name = "simple-agent-framework-api-dev"
vars = { ENVIRONMENT = "development" }

